--#Create Database
CREATE DATABASE OnlineBookstore;
USE OnlineBookstore; 
CREATE TABLE Books(
Book_ID SERIAL PRIMARY KEY,
Title VARCHAR(100),
Author VARCHAR(100),
Genre VARCHAR(50),
Published_year INT,
Price NUMERIC(10,2),
Stock INT
);

CREATE TABLE Customers (
Customer_ID SERIAL PRIMARY KEY,
Name VARCHAR(100),
Email VARCHAR(100),
Phone VARCHAR(15),
City VARCHAR(50),
Country VARCHAR(150)
);

CREATE TABLE Orders (
Order_ID SERIAL PRIMARY KEY,
Customer_ID INT REFERENCES Customers(Customer_ID),
Book_ID INT REFERENCES Books(Book_ID),
Order_Date DATE,
Quantity INT,
Total_Amount NUMERIC(10,2)
);
select * froM Books;

--- 1) REETRIEVE ALL BOOKS IN THE "FICTION" GENRE:
SELECT * FROM Books 
WHERE genre = "fiction";

--- 2) FIND BOOKS PUBLISHED AFTER THE YEAR 1950:
SELECT * FROM Books 
WHERE Published_year > 1950;

--- 3) LIST ALL THE CUSTOMERS FROM THE CANADA:
SELECT * FROM CUSTOMERS 
WHERE Country = "Canada";

--- 4) SHOW ORDERS PLACED IN NOVEMBER 2023:
SELECT * FROM Orders
WHERE Order_date BETWEEN '2023-11-01' AND '2023-11-30';

--- 5) RETRIEVE THE TOTAL STOCK OF BOOKS AVAILABLE:
SELECT SUM(Stock) 
FROM Books;

--- 6) FIND THE DETAILS OF THE MOST EXPENSIVE BOOK:
SELECT * FROM Books
ORDER BY Price DESC ;

--- 7) SHOW ALL CUSTOMERS WHO ORDERED MORE THAN 1 QUANTITY OF A BOOK:
SELECT * FROM Orders
WHERE Quantity > 1;

--- 8) RETRIEVE ALL ORDERS WHERE THE TOTAL AMOUNT EXCEEDS $20:
SELECT * FROM Orders
WHERE Total_amount > 20;

--- 9) LIST ALL THE GENRE AVAILABLE IN THE BOOKS TABLE:
SELECT DISTINCT genre FROM Books;

--- 10) FIND THE BOOKS WITH THE LOWEST STOCK:
SELECT * FROM Books
ORDER BY Stock ASC LIMIT 1;
